tsangjustin/taylorfit

package-lock.json
package.json
yarn.lock

closes #2
- Upgrade package version
- Running `npm audit`
- Making sure I can still start server and view platform

Upgrade dependency version for vulnerability fix

---

engine/model/Model.js
engine/worker/engine-worker.js
interface/adapter/worker.coffee
interface/components/Model.coffee
interface/components/grid/index.coffee
interface/components/grid/index.pug
interface/components/transform/index.coffee

- If user only imports fit data and does transformation, need to propogate those changes to cross and validation dataset when imported.
- Try all funcitonality when all data labels imported
- Just import fit data, do all transformation and import cross and validate dataset to see if data propogate

Transform: Propogate transformation to cross/validation dataset

---

engine/labels.json
engine/matrix/Matrix.js
engine/model/Model.js
engine/statistics/definitions.js
engine/statistics/index.js
engine/statistics/metadata.json
engine/worker/engine-worker.js
interface/adapter/worker.coffee
interface/components/Model.coffee
interface/components/candidates/index.coffee
interface/components/content/index.pug
interface/components/grid/index.coffee
interface/components/grid/index.pug
interface/components/index.coffee
interface/components/transform/index.coffee
interface/components/transform/index.pug
interface/components/transform/index.styl
interface/components/transform/label.json

- Add feature to transform column
- Transform column shows up as candidate
- Can no longer use original column in model

Transform column: Log

---

interface/components/Model.coffee

- Need to ignore transform colum that are deleted and represented as undefined value in the tranform_column object in Model

Fix transform col undefined

---

engine/model/Model.js
engine/statistics/definitions.js
engine/worker/engine-worker.js
interface/adapter/worker.coffee
interface/components/Model.coffee
interface/components/autocorrelation/index.coffee
interface/components/grid/index.coffee
interface/components/grid/index.pug
interface/components/histogram/index.coffee
interface/components/xyplot/index.coffee

From any column in the model, select "Show Sensitivity" from the drop down menu, to make a new column containing the sensitivity statistic for the selected column to appear.
When a sensitivity column already exists, the drop down option changes to "Hide Sensitivity". The sensitivity column can also be hidden directly from its own dropdown.
Sensitivity column is not included in available parameters to train the model. It can be plotted as a histogram and as a xy plot. It is also included in the csv created by "Export Data".

Add Sensitivity Feature

---

interface/components/export-code/exporter.js
interface/components/export-code/index.coffee
interface/components/export-code/index.pug

Add R syntax to Copy Model button and suppress C++ message

Add R syntax to Copy Model button

---

interface/components/result/index.coffee
interface/components/result/index.pug

- UI will round scientific notation numbers to 7 decimal places

R^2 Rounding

---

interface/components/export-code/exporter.js

Reorder the polynomial in descending order 
A model with no terms at all returns a zero
Correctly list all variables in the equation as functions's arguments

Reorder the polynomial in descending order and fix some errors 

---

interface/components/graph/index.coffee
interface/components/xyplot/index.coffee

Use transform property to check if the SVG element is on the top position of y axis
Sample plots downloaded:

Graph download button

---

engine/model/Model.js
engine/worker/engine-worker.js
interface/adapter/worker.coffee
interface/components/Model.coffee
interface/components/candidates/index.coffee
interface/components/candidates/index.pug
interface/components/result/index.coffee
interface/components/result/index.pug
interface/components/settings/index.coffee

Fixed bugs related to Sensitivity column:
1. Fixed calculation error when model has parameters in format: 123 * x * y
2. Sensitivity updates on model change:
- New parameter added from candidates term pane
- Parameter deleted from main grid
- Model cleared from settings pane
Note: Update sensitivity is being affected by refresh issue seen previously - to be fixed.

Fixed Sensitivity Bugs

---

interface/components/data-partition/index.styl

- Add style to Data Partition Modal

Add UI styling to data partition

---

interface/components/histogram/index.coffee

Fixes error that shows up when histogram is opened for Dependent, Predicted, or Residual columns.

Fix histogram sensitivity bug

---

package-lock.json
package.json
template/google-analytics.html
template/index.hbs
webpack.config.js
yarn.lock

- Integrate Google Analytics into website

Google Analytics

---

template/index.hbs

- Remove JSON stringify that adds quote around title

Fix Title Bar

---

interface/components/histogram/index.coffee
interface/components/histogram/index.pug

- Correctly download the plot when the first bar is clipped
- Use Sturges' formula to determine the optimal number of buckets

Fix histogram

---

build/index.html
interface/components/grid/index.pug

- Add build change to remove quotations
- Change render of dropdown to right

Change dropdown render position

---

engine/model/Model.js
engine/statistics/definitions.js
engine/worker/engine-worker.js
interface/adapter/worker.coffee
interface/components/Model.coffee
interface/components/autocorrelation/index.coffee
interface/components/candidates/index.coffee
interface/components/candidates/index.pug
interface/components/cumulative-distribution/index.coffee
interface/components/grid/index.coffee
interface/components/grid/index.pug
interface/components/histogram/index.coffee
interface/components/qqplot/index.coffee
interface/components/result/index.coffee
interface/components/result/index.pug
interface/components/settings/index.coffee
interface/components/xyplot/index.coffee

Add ability to calculate Importance Ratio and view in column per variable, similar to Sensitivity.

Add importance Ratio Column

---

interface/components/cumulative-distribution/index.coffee
interface/components/grid/index.pug
interface/components/qqplot/index.coffee

Add 2 plotting options(cumulative distribution plot and QQ plot) to extra columns' dropdown menu

Add new items to Extra columns' dropdown menu

---

interface/components/qqplot/index.coffee
interface/components/qqplot/index.pug

QQ plot for data with same values

Fix QQ Plot

---

engine/statistics/distributions-socr.js
interface/components/Model.coffee
interface/components/autocorrelation/index.coffee
interface/components/grid/index.coffee
interface/components/grid/index.pug
interface/components/histogram/index.coffee
interface/components/xyplot/index.coffee

confidence interval and prediction interval

confidence interval and prediction interval

---

interface/components/autocorrelation/index.coffee
interface/components/graph/index.coffee
interface/components/graph/index.styl
interface/components/histogram/index.coffee
interface/components/result/index.coffee
interface/components/result/index.pug
interface/components/result/index.styl

Reverts tsangjustin/taylorfit#49

Revert "R graph hist"
